# Generated by Django 3.2.9 on 2021-11-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211120_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topings',
            name='price',
        ),
        migrations.AlterField(
            model_name='topings',
            name='topings',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
