# Generated by Django 3.2.9 on 2021-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211127_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinner',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name': 'Pasta', 'verbose_name_plural': 'Pastas'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'verbose_name': 'Ensalada', 'verbose_name_plural': 'Ensaladas'},
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name': 'Sub', 'verbose_name_plural': 'Subs'},
        ),
        migrations.AlterModelOptions(
            name='topings',
            options={'verbose_name': 'Topping', 'verbose_name_plural': 'Toppings'},
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(verbose_name='Preciopasta'),
        ),
        migrations.AlterField(
            model_name='salads',
            name='price',
            field=models.FloatField(verbose_name='Preciosalad'),
        ),
    ]
