# Generated by Django 3.2.9 on 2021-11-29 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20211128_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='tiempo')),
                ('estado', models.IntegerField(choices=[(0, 'cancelado'), (1, 'pendiente'), (2, 'realizado')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='detallepizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('price', models.FloatField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.ordenes')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pizza')),
                ('toppings', models.ManyToManyField(to='orders.Topings')),
            ],
        ),
        migrations.CreateModel(
            name='detallepasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('price', models.FloatField(verbose_name='precio')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='orders.ordenes')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pasta')),
            ],
        ),
    ]
