# Generated by Django 3.2.9 on 2021-12-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211130_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepasta',
            options={'verbose_name': 'detallePasta', 'verbose_name_plural': 'detallePastas'},
        ),
        migrations.AlterModelOptions(
            name='ordenes',
            options={'verbose_name': 'Ordenes', 'verbose_name_plural': 'ordenes'},
        ),
    ]
