# Generated by Django 3.2.9 on 2021-12-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211201_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepasta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordenes',
            options={},
        ),
        migrations.AddField(
            model_name='ordenes',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
